### ISSUE TITLE
Output vocabulary not pruned

### ISSUE THREAD

**Issue by mallamanis** [muralisr/friendly-octo-couscous#3]
As far as I can understand, the output vocabulary is not pruned [here](https://github.com/muralisr/friendly-octo-couscous/blob/591f6e8538bdd31cf9b3c96bc58ae895067e740b/training_rnn.py#L200). Because some very rare names (e.g. those that appear only 1-2 times in your training corpus) are unlikely to appear in your test corpus, these should be pruned to a single `UNK` name.

During test, when you predict an `UNK` the model will imply that a new, but unknown name, is to be used for the given variable.

**Comment by muralisr** [comment]
this is done now, i am picking top N occurring output vocabulary now.
