### ISSUE TITLE
Is MSE loss the right one?

### ISSUE THREAD

**Issue by mallamanis** [muralisr/friendly-octo-couscous#4]
I see that you are using [here](https://github.com/muralisr/friendly-octo-couscous/blob/591f6e8538bdd31cf9b3c96bc58ae895067e740b/training_rnn.py#L123) a mean squared error loss. I am not sure if this is because you were testing this. Context2Name seems to be using cross-entropy loss over the output vocabulary, instead.

**Comment by muralisr** [comment]
yes, i am now using cross-entropy in the more recent version, thanks.
